---
version: "3.9"
services:
  oracle:
    image: container-registry.oracle.com/database/free:23.3.0.0
    ports:
      - 1521:1521
    environment:
      - ORACLE_PWD=$ORACLE_PWD
      - GRAPH_PWD=$GRAPH_PWD
      - GRAPH_USER=$GRAPH_USER
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./startup:/opt/oracle/scripts/startup
      - ./dataset:/home/oracle/dataset:rw
      - ./scripts:/home/oracle/scripts
volumes:
  oracle_data:
