---
version: "3.9"
services:
  oracle:
    image: container-registry.oracle.com/database/free:23.3.0.0
    ports:
      - 1521:1521
    environment:
      - DBA_PWD=$DBA_PWD
      - USR_PWD=$USR_PWD
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./setup:/opt/oracle/scripts/setup
      - ./dataset:/home/oracle/dataset
      - ./sqlcl:/home/oracle/sqlcl
      - ./scripts:/home/oracle/scripts
volumes:
  oracle_data:
